# Base image with C++ compiler
FROM gcc:latest

# Install CMake and GTest dependencies
RUN apt-get update && \
    apt-get install -y cmake && \
    apt-get clean

# Set working directory
WORKDIR /app

# Copy the whole project
COPY . .

# Build test targets
RUN mkdir build && cd build && cmake .. && make

# Run tests
CMD ["./build/runTests"]